Importing Dependencies

In [1]:
import pandas as pd
import numpy as np

*   Import Dataset -> Dialogues
*   The type of character a person has depends on the dialogues they spoke
*   Read the dialogues and determine the traits of character

In [31]:
# dataframe with pandas
df = pd.read_json(r'data\script-bag-of-words.json')

In [4]:
df.tail()

,episodeAlt,seasonNum,episodeNum,episodeTitle,text
68,S8E2,8,2,A Knight of the Seven Kingdoms,"[{'name': 'Daenerys Targaryen', 'text': 'About..."
69,S8E3,8,3,The Long Night,"[{'name': 'Northman #1', 'text': 'Oi!'}, {'nam..."
70,S8E4,8,4,The Last of the Starks,"[{'name': 'Jon Snow', 'text': 'And Everyone It..."
71,S8E5,8,5,The Bells,"[{'name': 'Lord Varys', 'text': 'And? Come Not..."
72,S8E6,8,6,The Iron Throne,"[{'name': 'Tyrion Lannister', 'text': 'I'll fi..."

In [32]:
df.iloc[-1]['text']

# data is in this format -> dictinary in a list

[{'name': 'Tyrion Lannister', 'text': "I'll find later. you"},
 {'name': 'Jon Snow', 'text': "It's Let me men not safe. send some with you."},
 {'name': 'Tyrion Lannister', 'text': "I'm alone. going"},
 {'name': 'Grey Worm',
  'text': 'Daenerys I In Queen, Targaryen, die. name of one sentence the the to true you'},
 {'name': 'Jon Snow',
  'text': "Grey It's These Worm! are men over. prisoners."},
 {'name': 'Grey Worm',
  'text': "It Queen's are defeated. enemies is not over the until"},
 {'name': 'Davos Seaworth',
  'text': "How They're be? defeated do knees. more much on their them to want you"},
 {'name': 'Grey Worm', 'text': 'They are breathing.'},
 {'name': 'Davos Seaworth', 'text': 'Look We around friend. won. you,'},
 {'name': 'Grey Worm', 'text': "I commands, my not obey queen's yours."},
 {'name': 'Jon Snow', 'text': "And Queen's are commands? the what"},
 {'name': 'Grey Worm',
  'text': '"Kill Cersei Lannister." These They all are chose fight follow for free her. men. to who'},
 {'name': 'Davos Seaworth',
  'text': 'Easy! Easy, Easy. Jon. Queen. We men. should speak the with'},
 {'name': 'Dothraki Bloodrider #1', 'text': 'Hyah!'},
 {'lang': 'Dothraki',
  'name': 'Daenerys Targaryen',
  'translation': 'Blood Kingdoms! Seven You You You You all blood. down enemies gave houses. in iron kept killed me me. my my of promises stone suits. the their their to tore your',
  'text': ''},
 {'lang': 'High Valyrian',
  'name': 'Daenerys Targaryen',
  'translation': "Grey I Master Plaza Pride. Queen's War. Worm. You You all are beside bravest commander forces, have loyal me men, most my name of of of of of since soldiers. the the the the walked you",
  'text': ''},
 {'lang': 'High Valyrian',
  'name': 'Daenerys Targaryen',
  'translation': "All But Dorne, From Isles Jade King's Landing Lannisport Now... Qarth, Sea! Summer Unsullied. We Will Winterfell Women, You a all and and are arms as beneath break children down freed from from from from grip have have have is lay liberated liberators! long me? men mothers' not not of of of of our over. people people raised slaves. spears suffered the the the the the the the the the to to to too torn tyrant! until war we were wheel wheel. will with world! you you you your",
  'text': ''},
 {'name': 'Daenerys Targaryen',
  'text': 'You You brother. committed freed treason. your'},
 {'name': 'Tyrion Lannister',
  'text': 'And I a brother. city. freed my slaughtered you'},
 {'lang': 'High Valyrian',
  'name': 'Daenerys Targaryen',
  'translation': 'Take him.',
  'text': ''},
 {'name': 'Jon Snow', 'text': 'Hey, What are doing happened? here? what you'},
 {'name': 'Arya Stark',
  'text': 'Cersei. I Your came first. got kill queen there to'},
 {'name': 'Jon Snow', 'text': "She's everyone's now. queen"},
 {'name': 'Arya Stark', 'text': 'Sansa. Try telling'},
 {'name': 'Jon Snow',
  'text': "I'll Wait city come find for gates. me outside the you."},
 {'name': 'Arya Stark',
  'text': "And I I Jon. She Who You'll a a always are. are. be her. killer know knows one. really see threat to when who you you"},
 {'name': 'Tyrion Lannister', 'text': 'Did any bring wine? you'},
 {'name': 'Jon Snow', 'text': 'No.'},
 {'name': 'Tyrion Lannister',
  'text': '"See, Ah... I I I I\'m I\'m It Now Our So Varys\'s Well... a after alive and ashes ashes: betrayed burn. can closest coming crude death? doesn\'t for for friend going. him is just justice. keep kind knows life long. man me. me. my my occurred of only prisoners queen see suppose talking tell thank the there there\'s to to to told watched where who you you."'},
 {'name': 'Jon Snow', 'text': "I've Not seen. that"},
 {'name': 'Tyrion Lannister',
  'text': 'I I I I I Oblivion a be best betrayed could crossbow. father for. hope is lover. my my my own queen. shot should strangled thankful. the with'},
 {'name': 'Jon Snow', 'text': "You didn't."},
 {'name': 'Tyrion Lannister',
  'text': "And I I I'd I've I've King's Landing The again, chose did did. do fate. it my not. now of people seen seen. that what"},
 {'name': 'Jon Snow',
  'text': "But I I can't happened. is justify now. over the try. war what won't"},
 {'name': 'Tyrion Lannister',
  'text': "And Bay. Is King's Landing. She She Slaver's When all. and are did done fighting? free... go heard her her it? liberated liberated liberating like of of of on people people people rules she she she'll soldiers, someone sound talking the the the the them to until who's world you"},
 {'name': 'Jon Snow',
  'text': "And Until been by counseling her her. side, today. you've"},
 {'name': 'Tyrion Lannister',
  'text': "I I It Our Until Varys and blood. could fire guide her. is nature queen's right. think to today. vanity was was was wrong."},
 {'name': 'Jon Snow',
  'text': "I'd Lannister. She's Then Tywin You and and are are? be blood, bodies born father, fire her house more no not on our our stamped than that's think too. we we're when who words you're"},
 {'name': 'Tyrion Lannister',
  'text': "My My Pile a all all an an as as be beautiful bodies day. ever evil evil father half in killed, man. many of our people queen single sister slaughtered still the the there they up was was woman. won't"},
 {'name': 'Jon Snow', 'text': 'Cersei choice. her left no'},
 {'name': 'Tyrion Lannister',
  'text': 'The battle fell, gates moment over. the the was'},
 {'name': 'Jon Snow',
  'text': 'She She beheaded. dragon friend her her of out saw saw shot sky. the'},
 {'name': 'Tyrion Lannister', 'text': 'And a burned city down for it. she'},
 {'name': 'Jon Snow',
  'text': "Aye, battlefield. easy far from it's judge standing the to when you're"},
 {'name': 'Tyrion Lannister', 'text': 'Would done have it? you'},
 {'name': 'Jon Snow', 'text': 'What?'},
 {'name': 'Tyrion Lannister',
  'text': "Would You've You've a back. been burned city down? dragon's had have on power. that the there, up you"},
 {'name': 'Jon Snow', 'text': "I don't know."},
 {'name': 'Tyrion Lannister',
  'text': "Yes, You because betray but do. don't her... know. say to want won't you you you"},
 {'name': 'Jon Snow', 'text': "I'd What's do? it matter what"},
 {'name': 'Tyrion Lannister',
  'text': "After And Astapor, Dothraki Everywhere I'm If It Meereenese She The They They When When a alive? all, and and and and anything. argue? believed believed believes better between build burned but cheer complained. could crucified destiny die done everyone. evil evil evil for for goes, good grows have her her her. hundreds if is is it, it. khals kill matters men men. men. more more more murdered no nobles, of of one paradise? powerful right. she she she she she she slavers slavers stood sure sure than that that... the the they to to truly we were were who whoever world worse would wouldn't you you you you"},
 {'name': 'Tyrion Lannister',
  'text': 'But I I I Look Love Not We all all as as at believed brother. heart. her her, her. in is know know love love more my my powerful reason. successfully than that. too. with you you.'},
 {'name': 'Jon Snow', 'text': '"Love death duty." is of the'},
 {'name': 'Tyrion Lannister', 'text': 'You came just that? up with'},
 {'name': 'Jon Snow', 'text': 'Aemon Maester a ago. it long said time'},
 {'name': 'Tyrion Lannister',
  'text': "And Do I'm I'm Iron It's It's No Sometimes Throne? Who Who You a also always are asking. cost, dangerous death do duty execute? greatest guards heir is is is last love. man matter men. more now? of of people people. protect realms right right rightful she'll shield terrible than that the the the the the the the the the the the thing thing. thing. think threat to to to to tried tried you you've you've"},
 {'name': 'Jon Snow',
  'text': "I'm Queen. She That's came decision. her is it sorry the this. to"},
 {'name': 'Tyrion Lannister',
  'text': 'And Do bending knee? see sisters? the them you your'},
 {'name': 'Jon Snow', 'text': 'My be loyal sisters the throne. to will'},
 {'name': 'Tyrion Lannister',
  'text': "Because Dany Sansa Why about be do doesn't me queen. she the think to told truth want you you?"},
 {'name': 'Jon Snow', 'text': "She choose. doesn't get to"},
 {'name': 'Tyrion Lannister',
  'text': 'And But No. choose do. have now. to you you'},
 {'name': 'Daenerys Targaryen',
  'text': "1,000 1,000 20? Aegon's Aegon's I I So What When a a a brother can't climb. could count do enemies, enemies. fallen fallen feet. from girl girl, high imagined in it like little look made many me mind mountain my of of of only see soles swords swords swords the the to to told too was was who with you"},
 {'name': 'Jon Snow',
  'text': 'I Lannister They acting executing in on orders. prisoners said saw street. the them they were your'},
 {'name': 'Daenerys Targaryen', 'text': 'It necessary. was'},
 {'name': 'Jon Snow',
  'text': 'Children, Have Have Necessary? been burned! children, down little seen? there? you you'},
 {'name': 'Daenerys Targaryen',
  'text': 'Cersei. I She She a against as cripple innocence it make me. me. peace their thought to tried used weapon with would'},
 {'name': 'Jon Snow', 'text': 'And Tyrion?'},
 {'name': 'Daenerys Targaryen',
  'text': "He How back behind broke conspired done enemies. even have heart? it my my people same the to treated when who've with you you, your"},
 {'name': 'Jon Snow', 'text': 'Forgive him.'},
 {'name': 'Daenerys Targaryen', 'text': "I can't."},
 {'name': 'Jon Snow',
  'text': 'Dany. Make Please, You You a all can can. forgive made make mistake. of see them them them, they understand.'},
 {'name': 'Daenerys Targaryen',
  'text': "The We be behind built by can't have. hide loyal men mercies. need small the to we we won't world world"},
 {'name': 'Jon Snow',
  'text': 'It The a be. has is mercy. need of to we world world'},
 {'name': 'Daenerys Targaryen',
  'text': "A And It's be. been before. easy good it never not see something that's to will world."},
 {'name': 'Jon Snow',
  'text': "How How be do do good? it'll know know? you you"},
 {'name': 'Daenerys Targaryen',
  'text': 'And Because I do good. is know so what you.'},
 {'name': 'Jon Snow', 'text': "I don't."},
 {'name': 'Daenerys Targaryen',
  'text': "You You You've always do. do. known."},
 {'name': 'Jon Snow',
  'text': "All What about else? everyone good. know other people the they think what's who"},
 {'name': 'Daenerys Targaryen',
  'text': "20. Be Build I It They This We We a a a and bastard's been beginning, boy break choose. couldn't count do don't from get girl has is it little little me. me. name new our reason. since the the the to to together. together. was were wheel who with with with world you"},
 {'name': 'Jon Snow', 'text': 'Now, You always. and are my queen.'},
 {'name': 'Sansa Stark', 'text': "Jon? Where's"},
 {'name': 'Grey Worm', 'text': 'He is our prisoner.'},
 {'name': 'Sansa Stark',
  'text': 'Lord So They Tyrion. be both brought gathering. is this to to were'},
 {'name': 'Grey Worm',
  'text': 'This We city decide do is now. our our prisoners. we what will with'},
 {'name': 'Sansa Stark',
  'text': "If Jon Northmen Snow city, explain find harming in interest. is look not of of outside the thousands to walls who why will you you you'll your your"},
 {'name': 'Grey Worm',
  'text': 'And Unsullied believe find is. it of that thousands who will you'},
 {'name': 'Yara Greyjoy',
  'text': 'Daenerys I Ironborn Some Targaryen. The are be follow forgive. may not. of quick swore to to you'},
 {'name': 'Sansa Stark', 'text': 'You a follow swore to tyrant.'},
 {'name': 'Yara Greyjoy',
  'text': 'Cersei Jon Let She Snow Unsullied a a and because deserves. freed from give gone he heart. her her, him in is knife of put the tyrant. us what'},
 {'name': 'Arya Stark',
  'text': "I'll Say about and another brother cut killing my throat. word your"},
 {'name': 'Davos Seaworth',
  'text': "Am Friends, Good House I If Make Nudho. Reach. Start The There This Thousands Torgo Unsullied We We've We've You a a and are as bannermen. been better but can country cutting dead. debt each ends. enough enough. find for gone. had how in is it it it it know land land. let live long lost men, need never of of other's owes own own. people please. properly? repay, saying that that the the the the them. there thousands throats to to try. us used war war. way. we weren't with with would've you you you, your your your your"},
 {'name': 'Grey Worm',
  'text': 'Jon Snow We We cannot do free. go justice. need need not payment.'},
 {'name': 'Tyrion Lannister', 'text': "It's decide. for not to you"},
 {'name': 'Grey Worm',
  'text': 'Everyone You are enough from has heard here not speak! to words you.'},
 {'name': 'Tyrion Lannister',
  'text': "And But His Jon Or You're any better committed crime decide. decide. fate for for for here. his is it's it. king no not one's our our queen. right. to to you"},
 {'name': 'Yohn Royce', 'text': "We a don't have king or queen."},
 {'name': 'Tyrion Lannister',
  'text': "Choose Westeros. You're in most one. people powerful the"},
 {'name': 'Grey Worm', 'text': 'Make choice, then. your'},
 {'name': 'Edmure Tully',
  'text': 'A And I I I My What and and annals as before country. decide experience has history. important in in is ladies... led like lives. lords lords moment most my of of of of one our reverberate senior skill small some stand statecraft suppose the the the the think this through to to today two underst... veteran wars. we will you'},
 {'name': 'Sansa Stark', 'text': 'Please Uncle? sit.'},
 {'name': 'Yohn Royce', 'text': 'Well, choose have someone. to we'},
 {'name': 'Samwell Tarly',
  'text': "Houses, Maybe Um, Um... We Why about ahem... all and be best but choose, decision everyone everyone. for great just just ladies. left lords over represent rule should the the they to... us? we well, what's whomever won't"},
 {'name': 'Edmure Tully',
  'text': 'Maybe a as dogs give should the vote we well.'},
 {'name': 'Yohn Royce', 'text': "I'll ask horse. my"},
 {'name': 'Edmure Tully', 'text': 'I crown. suppose the want you'},
 {'name': 'Tyrion Lannister',
  'text': "Can't Daenerys, Half Imp? Me? The a betraying choice. for for half hate hate her. me me of other people serving the the think worse"},
 {'name': 'Davos Seaworth', 'text': 'Who, then?'},
 {'name': 'Tyrion Lannister',
  'text': "About About And Armies? Bran Broken? Flags? Gold? He He He I've No Nothing Our Raven. Stories. The The There's Three-Eyed Wall, What Who a a a a again, all and and became better better beyond births, bloody boy boy, but can can crippled crossed defeat defeats, do enemy famines. fell few fly. from future? good had has he he'd high history. in into is it. it. keeper knew lead learned lived. made. massacres, memory, mistakes mm, more never nothing nothing of our our our our our past past. people? powerful so stop stories. story. story... than than the the the the the the the these think to to to tower triumphs, unites us walk wars, we've weddings, weeks. who who world"},
 {'name': 'Sansa Stark',
  'text': "Bran and can't children. father has he in interest no ruling"},
 {'name': 'Tyrion Lannister',
  'text': "But From Good. His I I I Kingdoms Realm. Seven Sons That They Westeros... Will abilities about and and as ask be be be best born. break. by can care choose chosen crown? cruel day day? don't don't from if is it. kings know know know. ladies last lead lords never not now now, of of of on on, our power. queen rulers serve spot stupid, the the the the the the this this to to to torment until us. want wanted we wear well wheel will will will will you you you you you you you... your your"},
 {'name': 'Bran Stark', 'text': 'I Why all came do think this way? you'},
 {'name': 'Tyrion Lannister',
  'text': 'Brandon House I Stark... To aye. of say'},
 {'name': 'Samwell Tarly', 'text': 'Aye.'},
 {'name': 'Edmure Tully', 'text': 'Aye.'},
 {'name': 'Lord #1', 'text': 'Aye.'},
 {'name': 'Lord #2', 'text': 'Aye.'},
 {'name': 'Yohn Royce', 'text': 'Aye.'},
 {'name': 'Robin Arryn', 'text': 'Aye.'},
 {'name': 'Dornish Lord', 'text': 'Aye.'},
 {'name': 'Yara Greyjoy', 'text': 'Aye.'},
 {'name': 'Lord #3', 'text': 'Aye.'},
 {'name': 'Lord #4', 'text': 'Aye.'},
 {'name': 'Gendry', 'text': 'Aye.'},
 {'name': 'Davos Seaworth', 'text': "I I'm a aye. but get not sure vote,"},
 {'name': 'Brienne of Tarth', 'text': 'Aye.'},
 {'name': 'Sansa Stark',
  'text': "And But Great I I North Northmen The War Westeros. You'll a again. all always an and as be brother. defending ever fell for fought good hard have in independent it king. kingdom, kneel little love much of of of of remain seen survived tens the those thousands thousands to too too was who will will. years. you,"},
 {'name': 'Tyrion Lannister',
  'text': 'All Andals Bran Broken, First First His King Kingdoms Lord Men, Name, Protector Realm. Six and and hail of of of of the the the the the'},
 {'name': 'Samwell Tarly', 'text': 'All Bran Broken! hail the'},
 {'name': 'Edmure Tully', 'text': 'All Bran Broken! hail the'},
 {'name': 'Lord #1', 'text': 'All Bran Broken! hail the'},
 {'name': 'Lord #2', 'text': 'All Bran Broken! hail the'},
 {'name': 'Yohn Royce', 'text': 'All Bran Broken! hail the'},
 {'name': 'Robin Arryn', 'text': 'All Bran Broken! hail the'},
 {'name': 'Dornish Lord', 'text': 'All Bran Broken! hail the'},
 {'name': 'Yara Greyjoy', 'text': 'All Bran Broken! hail the'},
 {'name': 'Lord #3', 'text': 'All Bran Broken! hail the'},
 {'name': 'Lord #4', 'text': 'All Bran Broken! hail the'},
 {'name': 'Gendry', 'text': 'All Bran Broken! hail the'},
 {'name': 'Davos Seaworth', 'text': 'All Bran Broken! hail the'},
 {'name': 'Brienne of Tarth', 'text': 'All Bran Broken! hail the'},
 {'name': 'Bran Stark', 'text': 'Hand. Lord Tyrion... be my will you'},
 {'name': 'Tyrion Lannister', 'text': "Grace, I N... No, Your don't it. want"},
 {'name': 'Bran Stark', 'text': "And I be don't king. to want"},
 {'name': 'Tyrion Lannister',
  'text': "Choose Choose Davos. I I I I I I I Ser anyone but but deserve didn't. don't else. it. knew right, thought thought was was wasn't. what wise,"},
 {'name': 'Bran Stark', 'text': 'I choose you.'},
 {'name': 'Grey Worm', 'text': 'You cannot.'},
 {'name': 'Bran Stark', 'text': "I I'm Yes, can. king."},
 {'name': 'Grey Worm', 'text': 'He This a criminal. deserves is justice. man'},
 {'name': 'Bran Stark',
  'text': "He He's He's fixing going got his it. just life made many mistakes. of rest spend terrible the them. to"},
 {'name': 'Grey Worm', 'text': 'It enough. is not'},
 {'name': 'Tyrion Lannister',
  'text': "Giving Letting Night's So Unsullied Watch. a a chosen free has king new our send start start the the to to to walk war. war. would would you you you"},
 {'name': 'Jon Snow', 'text': "Night's There's Watch? a still"},
 {'name': 'Tyrion Lannister',
  'text': "Arya Grey I No Sansa The The Unsullied Which Worm You a a a accepted always and and bastards broken but but children. compromise, course, father for freed, good happy. has head hold home is it's justice king lands, life make means men. need needs new no no no of of one our peace. sentence. shall suppose. take the they to understand very wanted wanted wife, will world you your"},
 {'name': 'Jon Snow', 'text': 'I Was What did? it right?'},
 {'name': 'Tyrion Lannister', 'text': 'What did. we'},
 {'name': 'Jon Snow', 'text': "It doesn't feel right."},
 {'name': 'Tyrion Lannister', 'text': '10 Ask again in me years.'},
 {'name': 'Jon Snow',
  'text': "I again. don't each ever expect other see we'll"},
 {'name': 'Tyrion Lannister',
  'text': "A Hand I King anyone as be edge few make of of off piss so sure. the the the to want world. would wouldn't years"},
 {'lang': 'Astapori Valyrian',
  'name': 'Unsullied #1',
  'translation': 'All boarded. have men the',
  'text': ''},
 {'lang': 'Astapori Valyrian',
  'name': 'Grey Worm',
  'translation': 'Good. Isle Naath. We for of sail the',
  'text': ''},
 {'name': 'Sansa Stark',
  'text': 'Can I another been forgive had me? there way. wish you'},

Change the dataset pattern ... make it more clear

*   Add Charcter name
*   Add words(dialouge)
*   Add number of words

In [33]:
# df.iterrows() is a built-in function in Pandas
# It allows you to iterate over DataFrame rows as (index, Series) pairs.

dialouge = {}
for i, row in df.iterrows():
  for item in row['text']:
    if item['name'] in dialouge:
      # append
      dialouge[item['name']] += item['text']
    else:
      # create character
      dialouge[item['name']] = item['text']  + " "

In [34]:
len(dialouge) # gives total no of charcaters in GOT

817

Store key(names) and values(dialouges) in new DataFrame

In [35]:
new_df = pd.DataFrame()
new_df['character'] = dialouge.keys()
new_df['words'] = dialouge.values()

In [36]:
new_df.iloc[:,0:3].head()

       character                                              words
0           Will  Easy, boy. I've I've Wildlings a a do ever in ...
1   Waymar Royce  One They're What a and another before d'you ea...
2          Gared  Wall. We back head should the to Our They We W...
3       Jon Snow  Father's Go on. watching. And mother. yourBran...
4  Septa Mordane  Fine Well always. as done. work, I Quite beaut...

In [37]:
# count no of words each character spoke and add as a coloumn in new_df

new_df['num_words'] = new_df['words'].apply(lambda x:len(x.split()))
new_df = new_df.sort_values('num_words',ascending=False)
new_df = new_df.head(100)

# taking only top 100 characters out of 817 for low size & high effiecny

In [38]:
new_df.shape

(100, 3)

In [39]:
new_df.head()

,character,words,num_words
17,Tyrion Lannister,It Mmh. Northern about girls. is say the they ...,25924
13,Cersei Lannister,And And Casterly One Rock. When about afraid. ...,14294
3,Jon Snow,Father's Go on. watching. And mother. yourBran...,11488
20,Daenerys Targaryen,We've a and anything. asked been for for guest...,11202
12,Jaime Lannister,"As I It's brother, duty feel it's much. my sho...",10823

VECTORIZATION (Bag Of Word)

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english')
# stop_words is used to remove unwanted words(is,and,this,the) in statements

Embedding and Tokenization

In [41]:
embedding = cv.fit_transform(new_df['words']).toarray()

In [42]:
embedding.shape    # 100 characters and 15335 unique words on total

(100, 15335)

In [43]:
embedding = embedding.astype('float64')

Import t-SNE for visualization and dim reduction
TSNE is use for :
1.   understand patterns & relationships
2.   helps in clustering

In [44]:
from sklearn.manifold import TSNE

In [45]:
tsne = TSNE(n_components=2, verbose=1, random_state=123)
z = tsne.fit_transform(embedding)     # reduce embedding into 2D

[t-SNE] Computing 91 nearest neighbors...
[t-SNE] Indexed 100 samples in 0.005s...
[t-SNE] Computed neighbors for 100 samples in 0.128s...
[t-SNE] Computed conditional probabilities for sample 100 / 100
[t-SNE] Mean sigma: 14.377887
[t-SNE] KL divergence after 250 iterations with early exaggeration: 64.401108
[t-SNE] KL divergence after 800 iterations: 0.301372

In [46]:
z.shape

(100, 2)

In [47]:
# add new cols x and y
new_df['X'] = z.T[0]
new_df['Y'] = z.T[1]

In [48]:
new_df

,character,words,num_words,X,Y
17,Tyrion Lannister,It Mmh. Northern about girls. is say the they ...,25924,-3.342438,0.753784
13,Cersei Lannister,And And Casterly One Rock. When about afraid. ...,14294,-3.092457,0.733753
3,Jon Snow,Father's Go on. watching. And mother. yourBran...,11488,-2.974039,0.970400
20,Daenerys Targaryen,We've a and anything. asked been for for guest...,11202,-2.586169,0.337781
12,Jaime Lannister,"As I It's brother, duty feel it's much. my sho...",10823,-2.908238,0.824755
...,...,...,...,...,...
132,Rickard Karstark,Castle I'll King North! Red The They and can c...,466,2.763872,3.781367
57,Syrio Forel,"Tomorrow You are at be boy. here late, midday....",462,3.403694,2.542524
112,Kevan Lannister,Tyrion. Catelyn Golden Jaime Lords River River...,460,3.141036,2.772262
365,Mace Tyrell,"From Grace, House Margaery May Reach, Tyrell Y...",450,3.128660,2.601798
49,Pypar,I before did. find if the they'd wolves wonder...,412,3.246231,2.201968

Plot the Graph

In [26]:
import plotly.express as px
fig = px.scatter(new_df.head(25), x="X", y="Y", color="character")
fig.show()

In [29]:
import pickle
with open('data.pkl', 'wb') as f:
	pickle.dump(new_df,f)